spring:
  application:
    name: dubbo-order
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.8.132:3306/zhou_order
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  registry:
    address: zookeeper://192.168.8.132:2181
server:
  port: 10089

mybatis:
  type-aliases-package: com.zhou.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
