#mybatis.configuration.map-underscore-to-camel-case=true

spring:
  application:
    name: dubbo-account-service
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.8.132:3306/zhou_account
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  scan:
    base-packages: com.zhou.service
  registry:
    address: zookeeper://192.168.8.132:2181
  protocol:
    port: -1
server:
  port: 6666

mybatis:
  type-aliases-package: com.zhou.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
