# Redis配置
spring:
  application:
    name: dubbo-inventory-service
#  main:
#    allow-bean-definition-overriding: true
#    web-application-type: none
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.8.132:3306/test
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.8.132
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
  cache:
    type: ehcache
    ehcache:
      config: eachche.xml

mybatis:
  type-aliases-package: com.zhou.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    cache-enabled: true
